# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20161130_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.TextField()),
                ('course_ch', models.TextField()),
                ('course_en', models.TextField()),
                ('category', models.TextField()),
                ('time', models.TextField()),
                ('teacher_ch', models.TextField()),
                ('teacher_en', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='published_date',
        ),
    ]
