# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20161220_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.Teacher'),
            preserve_default=False,
        ),
    ]
