# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-30 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20161230_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='image',
        ),
    ]
