# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='course',
        ),
    ]
