# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20170102_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='field',
            field=models.TextField(default='None'),
        ),
    ]
