# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='course.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='course_id',
        ),
        migrations.DeleteModel(
            name='Ranking',
        ),
    ]
