# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20170105_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='score',
        ),
        migrations.AddField(
            model_name='rating',
            name='score0',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='score1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='score2',
            field=models.IntegerField(default=0),
        ),
    ]
