# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20170105_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='score0',
            new_name='_score0',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='score1',
            new_name='_score1',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='score2',
            new_name='_score2',
        ),
    ]
